# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-09 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='S3Object',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=200, verbose_name='Name')),
                ('store_fname', models.CharField(max_length=200, verbose_name='Name')),
                ('url', models.URLField(verbose_name='File URL')),
                ('folder_key', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'db_table': 's3_object',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteBanner',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sequence', models.IntegerField(verbose_name='Sequence')),
            ],
            options={
                'db_table': 'website_banner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsitePolicy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sequence', models.IntegerField(verbose_name='Sequence')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'db_table': 'website_policy',
                'managed': False,
            },
        ),
    ]
