# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-22 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('code', models.CharField(max_length=2, verbose_name='Name')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'res_country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IrConfigParameters',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, verbose_name='key')),
                ('value', models.TextField(verbose_name='Value')),
            ],
            options={
                'db_table': 'ir_config_parameter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('is_company', models.NullBooleanField(verbose_name='Is Company')),
                ('city', models.CharField(blank=True, max_length=60, verbose_name='City')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'db_table': 'res_partner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'db_table': 'product_attribute',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('weight', models.FloatField(blank=True, verbose_name='Weight')),
                ('ratio', models.FloatField(blank=True, verbose_name='VG/PG Ratio')),
                ('wholesale_price', models.FloatField(blank=True, verbose_name='Wholesale Price')),
                ('msrp', models.FloatField(blank=True, verbose_name='MSRP')),
                ('old_price', models.FloatField(blank=True, verbose_name='Wholesale Price')),
            ],
            options={
                'db_table': 'product_attribute_value',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResUsers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=64, verbose_name='Login')),
            ],
            options={
                'db_table': 'res_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S3Object',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=200, verbose_name='Name')),
                ('store_fname', models.CharField(max_length=200, verbose_name='Name')),
                ('url', models.URLField(verbose_name='File URL')),
                ('folder_key', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'db_table': 's3_object',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteBanner',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sequence', models.IntegerField(verbose_name='Sequence')),
                ('file_name', models.CharField(max_length=100, verbose_name='File Name')),
            ],
            options={
                'db_table': 'website_banner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsitePolicy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sequence', models.IntegerField(verbose_name='Sequence')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'db_table': 'website_policy',
                'managed': False,
            },
        ),
    ]
