# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-09 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odoo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrConfigParameters',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, verbose_name='key')),
                ('value', models.TextField(verbose_name='Value')),
            ],
            options={
                'db_table': 'ir_config_parameter',
                'managed': False,
            },
        ),
    ]
