# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-09 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odoo', '0002_irconfigparameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'db_table': 'product_attribute',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'db_table': 'product_attribute_value',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Stone Name')),
            ],
            options={
                'db_table': 'product_template',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('active', models.NullBooleanField(verbose_name='Active')),
                ('shipping', models.NullBooleanField(verbose_name='Shipping')),
                ('sale_ok', models.NullBooleanField(verbose_name='Can be Sold')),
                ('type', models.CharField(choices=[('product', 'Stockable Product'), ('consu', 'Consumable Product'), ('service', 'Service')], max_length=20, verbose_name='Type')),
                ('lst_price', models.FloatField(blank=True, null=True, verbose_name='Total Price')),
                ('description', models.TextField(verbose_name='Remarks')),
            ],
            options={
                'db_table': 'product_product',
                'managed': False,
            },
        ),
    ]
