# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-18 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odoo', '0003_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionCodes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Code')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
