# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-18 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odoo', '0004_promotioncodes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotioncodes',
            options={'managed': False},
        ),
    ]
