# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-28 04:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odoo', '0005_auto_20170618_1356'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='promotioncodes',
            table='promotion_codes',
        ),
    ]
