# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-08 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odoo_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='odoouser',
            name='token_expiration',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Token Expiration'),
        ),
        migrations.AddField(
            model_name='odoouser',
            name='token_password',
            field=models.UUIDField(blank=True, null=True, verbose_name=b'Token'),
        ),
    ]
