# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-11 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'db_table': 'mail_mass_mailing_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsletterContact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
            ],
            options={
                'db_table': 'mail_mass_mailing_contact',
                'managed': False,
            },
        ),
    ]
