# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-09 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_hremployee_hrjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerReviews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sequence', models.IntegerField(verbose_name='Sequence')),
            ],
            options={
                'db_table': 'partner_reviews',
                'managed': False,
            },
        ),
    ]
