# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-09 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0003_partnerreviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteContactUs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('read', 'Viewed'), ('unread', 'Not Viewed')], max_length=10, verbose_name='State')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('website', models.URLField(verbose_name='Website')),
                ('comment', models.TextField(verbose_name='Comment')),
            ],
            options={
                'db_table': 'website_contactus',
                'managed': False,
            },
        ),
    ]
