# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-20 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0004_websitecontactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteNotifications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sequence', models.IntegerField(verbose_name='Sequence')),
                ('name', models.TextField(verbose_name='Notification')),
                ('active', models.NullBooleanField(verbose_name='Active')),
            ],
            options={
                'db_table': 'website_notifications',
                'managed': False,
            },
        ),
    ]
