# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-22 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlavorConcDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'flavor_conc_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FlavorReviews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('write_date', models.DateTimeField(auto_now=True)),
                ('write_uid', models.IntegerField(verbose_name='Write UID')),
                ('create_uid', models.IntegerField(verbose_name='Write UID')),
                ('rating', models.CharField(choices=[('0', 'Very Bad'), ('1', 'Bad'), ('2', 'Normal'), ('3', 'Good'), ('4', 'Very Good')], max_length=20, verbose_name='Rating')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'db_table': 'flavor_reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductFlavors',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('create_date', models.DateTimeField(verbose_name='Created Date')),
                ('file_name', models.CharField(max_length=100, verbose_name='Created Date')),
                ('short_description', models.TextField(verbose_name='Short Description')),
                ('long_description', models.TextField(verbose_name='Long Description')),
            ],
            options={
                'db_table': 'product_flavors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductTab',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tab_style', models.CharField(choices=[(1, 'Flavor Concentration Matrix'), (2, 'Product List'), (3, 'Marketing'), (4, 'Free Sample List'), (5, 'Free Sample Matrix')], max_length=20, verbose_name='Tab Style')),
                ('consumable_stockable', models.CharField(choices=[('product', 'Stockable Product'), ('consu', 'Consumable Product'), ('service', 'Service')], max_length=20, verbose_name='Product Type')),
                ('visible_all_customers', models.NullBooleanField(verbose_name='Visible to all customers')),
            ],
            options={
                'db_table': 'product_tab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Stone Name')),
                ('type', models.CharField(choices=[('product', 'Stockable Product'), ('consu', 'Consumable Product'), ('service', 'Service')], max_length=20, verbose_name='Type')),
                ('list_price', models.FloatField(blank=True, null=True, verbose_name='Total Price')),
                ('description', models.TextField(verbose_name='Remarks')),
                ('sale_ok', models.NullBooleanField(verbose_name='Can be Sold')),
            ],
            options={
                'db_table': 'product_template',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('active', models.NullBooleanField(verbose_name='Active')),
                ('shipping', models.NullBooleanField(verbose_name='Shipping')),
                ('file_name', models.CharField(max_length=100, verbose_name='File Name')),
            ],
            options={
                'db_table': 'product_product',
                'managed': False,
            },
        ),
    ]
