# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-14 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlavorConcDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'flavor_conc_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductFlavors',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('create_date', models.DateTimeField(verbose_name='Created Date')),
                ('file_name', models.CharField(max_length=100, verbose_name='Created Date')),
            ],
            options={
                'db_table': 'product_flavors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductTab',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tab_style', models.CharField(choices=[(1, 'Flavor Concentration Matrix'), (2, 'Product List'), (3, 'Marketing'), (4, 'Free Sample List'), (5, 'Free Sample Matrix')], max_length=20, verbose_name='Tab Style')),
                ('consumable_stockable', models.CharField(choices=[('product', 'Stockable Product'), ('consu', 'Consumable Product'), ('service', 'Service')], max_length=20, verbose_name='Product Type')),
                ('visible_all_customers', models.NullBooleanField(verbose_name='Visible to all customers')),
            ],
            options={
                'db_table': 'product_tab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Stone Name')),
            ],
            options={
                'db_table': 'product_template',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('product', 'Stockable Product'), ('consu', 'Consumable Product'), ('service', 'Service')], max_length=20, verbose_name='Type')),
                ('lst_price', models.FloatField(blank=True, null=True, verbose_name='Total Price')),
                ('description', models.TextField(verbose_name='Remarks')),
                ('active', models.NullBooleanField(verbose_name='Active')),
                ('sale_ok', models.NullBooleanField(verbose_name='Can be Sold')),
                ('shipping', models.NullBooleanField(verbose_name='Shipping')),
            ],
            options={
                'db_table': 'product_product',
                'managed': False,
            },
        ),
    ]
