# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-14 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlavorReviews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('write_date', models.DateTimeField(auto_now=True)),
                ('write_uid', models.IntegerField(verbose_name='Write UID')),
                ('create_uid', models.IntegerField(verbose_name='Write UID')),
            ],
            options={
                'db_table': 'flavor_reviews',
                'managed': False,
            },
        ),
    ]
