# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-08 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='S3Object',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=200, verbose_name='Name')),
                ('sequence', models.IntegerField(verbose_name='Sequence')),
                ('aboutus_banner', models.NullBooleanField(verbose_name='Is About us Banner ?')),
                ('contactus_banner', models.NullBooleanField(verbose_name='Is Contact us Banner ?')),
            ],
            options={
                'db_table': 's3_object',
                'managed': False,
            },
        ),
    ]
