# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-08 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_saleorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInvoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('number', models.CharField(max_length=100, verbose_name='Number')),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('proforma', 'Pro-forma'), ('proforma2', 'Pro-forma'), ('open', 'Not Paid Yet'), ('paid', 'Paid'), ('cancel', 'Cancelled')], max_length=20, verbose_name='State')),
                ('date_invoice', models.DateField(verbose_name='Invoice Date')),
                ('amount_total', models.FloatField(verbose_name='Amount Total')),
            ],
            options={
                'db_table': 'account_invoice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SaleOrderInvoiceRel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'sale_order_invoice_rel',
                'managed': False,
            },
        ),
    ]
