# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-30 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cart_id', models.UUIDField(editable=False)),
                ('note', models.TextField(verbose_name='Note')),
            ],
        ),
    ]
