# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-17 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartnote_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='partner_id',
            field=models.IntegerField(default=0, verbose_name='Partner ID'),
        ),
    ]
