# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-03 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartitem_partner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='checkedout',
            field=models.NullBooleanField(verbose_name='Checkedout ?'),
        ),
    ]
