# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-20 04:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20170220_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_cart_item_ids', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
